name: jingleplayer
channels:
  - defaults
dependencies:
  - python=3.10.12
  - pip=23.2.1
  - pip:
      - dbus-python~=1.3.2
      - freezegun~=1.2.2
      - humanize~=4.7.0
      - icalendar~=5.0.7
      - mutagen~=1.46
      - pandas~=2.0.3
      - playsound~=1.3.0
      - pytify~=3.6.3
      - pytimeparse~=1.1.8
      - reprint~=0.6.0
